apiVersion: v1
kind: Service
metadata:
  name: smart-event-service
  namespace: smart-event
spec:
  selector:
    app: smart-event-portal
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer
